branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
language: node_js
node_js:
- 14.2.0
cache:
  directories:
  - "~/.npm"
  - ".jest"
jobs:
  include:
  - stage: test
    if: commit_message !~ /(travis-deploy)/
    script:
    - yarn test:ci
  - stage: release
    if: branch = master AND (NOT type = pull_request) AND (commit_message !~ /(travis-deploy)/)
    script:
    - yarn semantic-release
  - stage: deploy
    if: branch = master AND (NOT type = pull_request) AND (commit_message =~ /(travis-deploy)/)
    deploy:
      provider: heroku
      app: homebar-server
      api_key:
        secure: qu2nyd+b3yMJijqRJRLBz/QO0Q6BH3h3IIHlXvBLfuex5zbOpkODDm1tR5DHpQcUird9ccqSoImMQneivNl08qtIdzvVFf8KSk11Ibn6kcBN8wmGMii9MJRlCOrJNaQDps+0rLlqWg1kdQ+zQZkIVGcPCynkUI/JepSo3tsAq9ZPumWprfxH5xoLzCyn+V2nYTKhzTxNUwT6j3EN50fC9OWNKYQgnU16ZG5Frh5YKArDMUAH2oUpw6ER7K2/hsnU2LomWsEp2bzgQHdMYY9IfObxu27dyaD1IimnEtJwBnjdVw9c3q3ghkzTKJLLH1hDqgDKNFUy9GHzYtFQ2LwSgKN0csh54z1+iRBpDmLm2M1EhcHU/SkRaO3nt/T9FbPLIRBUQhCnq2UmoLkl1YB9/ObzglTS5MNv1pVLjHxC5RzIHOEYN1cdWqSxalaO944HTL26maV2IxCU4vq1W5dAKnQzLoKGXbVtC6w1nAdQG4ZRNtjE16IxPBbCiWZJoNuCLTlVAJ2OWom2BURB4Qi9ZA7HjG5HrNnOZwCUqAhSplkUfaULfIt6fRYuUc7pgtEtN60J9aoq7QnHhK19i7cOvQTM0TvCbpEQZit1YAZbPNs6xZhD3WzoCNePk4KQGuOspkGUn4JmSdZfntGRdack73xYTovTBVZN7GgBYyLzfco=
